### PR TITLE
[1.46] shared abseil on windows + test overhaul

### PR DESCRIPTION
**Pull request by h-vetinari**
Picking up various improvements from #237, but switching to shared abseil builds on windows now.

### CODE REVIEW

**Comment by h-vetinari** [comment]
Yay, passing windows builds, including a full-fledged configure+build test for using the produced artefacts through cmake. 🥳

Unix still needs https://github.com/conda-forge/libprotobuf-feedstock/pull/127 (if we want to also switch on the cmake example)

@conda-forge/grpc-cpp @hmaarrfk

PS. For reasons that are completely inscrutable to me, the tests for `grpc-cpp` on windows do not run the file checks under `commands:`, or at least do not show their output. Not sure if the compiler activation is interfering with that. If we really want, we could also do a specific testing feedstock that gets triggered through `downstreams:` like libcxx [does](https://github.com/conda-forge/libcxx-feedstock/blob/main/recipe/meta.yaml#L84-L87) with libcxx-testing.

**Comment by hmaarrfk** [comment]
I don't think I'll be of much use to review and as such, i would like to take a back seat on this.

I think you have many capable users of the library that might be able to give you feedback better than i can.

I think i remember reading that "abseil shared will compile, but for some reason using it is problematic" which i don't really understand. As such, i would encourage you to build up as much of the stack as you can and try to test it for real.

It is possible to use conda forge infrastructure to upload to your own channel. It is great for experimenting purposes considering build locally doesn't work for windows. The manual steps i have to do is activate azure and enter in my binstar token there.

**Comment by h-vetinari** [comment]
> I don't think I'll be of much use to review and as such, i would like to take a back seat on this.

Fair enough.
 
> I think i remember reading that "abseil shared will compile, but for some reason using it is problematic" which i don't really understand.

The issue is precisely the ABI-impact of the C++ version (inluding the headers that come along with the shared lib). Most people aren't ready to take on the consequences of doing that, but our abseil unix builds have been shared for quite a while. 

> As such, i would encourage you to build up as much of the stack as you can and try to test it for real.
>
> It is possible to use conda forge infrastructure to upload to your own channel. It is great for experimenting purposes considering build locally doesn't work for windows. The manual steps i have to do is activate azure and enter in my binstar token there.

I can imagine this using a dev-channel that we can publish to (similar to `llvm_rc` or simply reusing the existing `abseil_dev` label) etc., but I don't think that's even necessary. The testing added in this PR should really put all worries to rest (including pkg-config!).

**Review by hmaarrfk — APPROVED** [review]
This looks really clean and high quality.

**Pull request merged**
