### PR TITLE
Rebuild for protobuf 4.25.1

### PR DESCRIPTION
**Pull request by h-vetinari**
Forgot this one before coupling the migrations 🤦

### CODE REVIEW

**Comment by h-vetinari** [comment]
Heroku issues -> no automerge.

**Comment by xylar** [comment]
@h-vetinari and @conda-forge/grpc-cpp, it seems that only OSX packages for `grpcio` from this PR are actually showing up on anaconda.org:
https://anaconda.org/conda-forge/grpcio/files

The outputs are shown at the bottom of the logs, but the only upload is for `libgrpc`:
https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/862890/logs/24

Any idea what's going wrong?

**Comment by xylar** [comment]
Also, I think maybe this needs to be removed (or set manually):
https://github.com/conda-forge/grpc-cpp-feedstock/blob/main/recipe/conda_build_config.yaml#L3

**Comment by xylar** [comment]
Ah, I'm pretty sure the issue was that the build number didn't get bumped. I'll make a PR to hopefully fix these issues.

**Pull request merged**
