### PR TITLE
DBG: fails of 1.65.4 h33d5ef

### PR DESCRIPTION
**Pull request by MementoRC**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by MementoRC** [comment]
@h-vetinari It seemed that everything built but win, which could be a missing DLL_EXPORT in grpc when linking grpc++. The issue I have is a recipe that requests `1.65.4`, though

**Comment by h-vetinari** [comment]
> The issue I have is a recipe that requests `1.65.4`, though

It seems hard to believe that 1.65.5 wouldn't equally work for that. Nothing should be pinning down to patch version here, the minor version determines the compatibility.

This PR is useless because the current state of main is incomplete (missing grpcio), because we've had bootstrapping issues with bazel and protobuf. Check out the other PR to see what's necessary to actually fix things

**Comment by MementoRC** [comment]
I did not mean to disagree or argue. I was only pointing out that the recipe I am working on has the version hard-pinned in its requirement, thus leading it to a fail with a mismatch between 1.62.2 and 1.64.4. Do you recommend to simply patch upstream to point to the available conda grpcio? I am trying to learn the preferred practices of conda-forge

**Comment by h-vetinari** [comment]
Things may change between minor versions, so those pins should ideally be respected (if we have the versions in conda-forge; hopefully we should soon be back to continuously releasing after the recent build system changes).

The ideal would be to open an issue upstream and make the case to not pin down to patch level. The second-best thing is to patch out the patch-level requirement on the feedstock. If you're changing the minor level pin as well, it's good to run the upstream test suite to ensure things still work as intended.

**Comment by MementoRC** [comment]
Thank you for the guidance. I was clumsily trying to find a solution for the tags and just saw that Uwe "magic-wanded-it" away., I'll proceed with a patch and await the chain of merges to continue testing.

**Pull request closed without merging**
