### PR TITLE
Rebuild and Pin new abseil

### PR DESCRIPTION
**Pull request by pitrou**
Make sure we require a specific abseil version, as they are incompatible with each other.

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by pitrou** [comment]
@conda-forge-admin, please rerender

**Comment by pitrou** [comment]
@conda-forge-admin, please rerender

**Comment by pitrou** [comment]
@xhochy

**Comment by pitrou** [comment]
```
+ cmake --build . --config Release --target install

ninja: error: '/home/conda/feedstock_root/build_artifacts/abseil-cpp_1582800857035/_build_env/powerpc64le-conda_cos7-linux-gnu/sysroot/usr/lib/librt.so', needed by 'check_epollexclusive', missing and no known rule to make it
```

**Comment by xhochy** [comment]
Will take care of this via a different route.

**Pull request closed without merging**
