### PR TITLE
add run_exports

### PR DESCRIPTION
**Pull request by CJ-Wright**
@isuruf

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@conda-forge/arm-arch any idea what is going on here?

**Comment by hmaarrfk** [comment]
Where is the aarch build?

**Comment by hmaarrfk** [comment]
Not too sure why the ppc build is failing. Looks like maybe a change in the host Travis image? Or in the dockerinage

**Comment by CJ-Wright** [comment]
@conda-forge-admin, rerender

**Pull request merged**
