### PR TITLE
Use run exports for 1.46

### PR DESCRIPTION
**Pull request by hmaarrfk**
This avoids the static libraries for zlib
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by h-vetinari** [comment]
You could have pushed that into #194... 🤷

**Comment by hmaarrfk** [comment]
Yeah. I kinda got confused. I think we need a build nunber bump there

**Comment by h-vetinari** [comment]
#194 had a new patch version, so no build bump necessary. :)

**Comment by hmaarrfk** [comment]
Nice catch

**Pull request merged**
