### PR TITLE
1.47.x abseil 20220630

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@hmaarrfk, what is the status here?  This seems to be something needed for https://github.com/conda-forge/google-cloud-cpp-feedstock/pull/105, which is in turn needed by https://github.com/conda-forge/google-cloud-bigquery-feedstock/pull/117.

I'd be happy to help but since the errors are under the Windows build, I'll be pretty useless.

**Comment by h-vetinari** [comment]
> @hmaarrfk, what is the status here?

Needs https://github.com/conda-forge/abseil-cpp-feedstock/pull/35 (as demonstrated in #196). It's ready to go, but since there were no responses from core, I've given a few more days before I hit the button.

**Comment by h-vetinari** [comment]
upstream requires at least C++14 [already](https://github.com/grpc/grpc/blob/v1.47.1/CMakeLists.txt#L230) for 1.47

@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
OK, I'm pretty sure this is a bug conda smithy. This PR uniformly sets `abseil_cpp='20220623.0'` while #194 takes  `abseil_cpp='20211102.0'`, seemingly at random. I have one more idea (make abseil-cpp appear in the deps of something) - however, it takes me way too long to rerender locally though, so I'm relying on the bot for this.

Sorry for the noise this generates.

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
If desired I can also do this with the migration yaml directly, but since Mark started with changing the cbc, I stayed with that.

**Comment by hmaarrfk** [comment]
I'm somewhat swamped with travel for now. so feel free to take over as needed.

**Comment by hmaarrfk** [comment]
i lost track of the abseil best practices

**Comment by h-vetinari** [comment]
> i lost track of the abseil best practices

Abseil basically says: don't do shared libs. But we have the means to track what's necessary (version/ABI) to make it work.

**Comment by h-vetinari** [comment]
> I'm somewhat swamped with travel for now. so feel free to take over as needed.

Thanks. To avoid further merge conflicts (and since Isuru also saw #196), I'm going to merge this now.

**Pull request merged**
